# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.20.1b0"
  openjdk_min: "17"
  jpype1_min: "1.5.0"

package:
  name: timefold
  version: ${{ version }}

source:
  - target_directory: dist
    url: https://pypi.org/packages/source/t/timefold/timefold-${{ version }}.tar.gz
    sha256: 9badcc71631fc6385443ac11fd1472d05bfeff772f540ee5e835e99e421df617
  - target_directory: src
    url: https://github.com/TimefoldAI/timefold-solver/archive/refs/tags/v${{ version | replace("b0", "") }}.tar.gz
    sha256: fef792c0fb09c185533ffe427f642222b6e70eac3afc71a7b321a610027741f9

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - jpype1 >=${{ jpype1_min }}
    - openjdk ${{ openjdk_min }}.*
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - stubgenj >=0.2.5
  run:
    - jpype1 >=${{ jpype1_min }}
    - openjdk >=${{ openjdk_min }}
    - python >=${{ python_min }}

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports: timefold
  - files:
      source:
        - src/python/python-core/tests/
    requirements:
      run:
        - openjdk ${{ openjdk_min }}.*
        - pytest-cov
        - python ${{ python_min }}.*
    script:
      - cd src/python/python-core/tests
      - coverage run --source timefold --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=70

about:
  homepage: https://timefold.ai/open-source-solver
  license_file: dist/LICENSE.txt
  license: Apache-2.0
  summary: An AI constraint solver that optimizes planning and scheduling problems
  repository: https://github.com/TimefoldAI/timefold-solver
  documentation: https://docs.timefold.ai/timefold-solver/latest

extra:
  recipe-maintainers:
    - bollwyvl
